branches/saulius-fight-memory-leaks/ (saulius@varanas.saulius-grazulis.lt) Adding possibility to skip certain tests if a check of their conditions (a .chk script) reports that their result will be inconclusive.
git-svn-id: svn+ssh://saulius.grazulis.lt/home/saulius/svn-repositories/compilers/branches/saulius-fight-memory-leaks@4147 f7c8cbe2-f9e6-0310-9050-d7f47bf15973

diff --git a/MasterMakefile b/MasterMakefile
--- a/MasterMakefile
+++ b/MasterMakefile
@@ -316,9 +316,18 @@ ${DIFF_FILES}: ${TARGET}
 
 ${DIFFIL_DIR}/%.diff: ${TARGET} ${TEST_DIR}/%${EXT}
 	-@printf "%-30s " "$*:" ; \
-	unset SL_INCLUDE_PATHS; \
-	./$^ ${TEST_OPTIONS} 2>&1 | diff -u ${OUTPUT_DIR}/$*.out - > $@ ; \
-	if [ $$? = 0 ]; then echo "OK"; else echo "FAILED:"; cat $@; fi
+	if [ ! -f ${TEST_DIR}/$*.chk ] || ${TEST_DIR}/$*.chk; then \
+		unset SL_INCLUDE_PATHS; \
+		./$^ ${TEST_OPTIONS} 2>&1 \
+			| diff -u ${OUTPUT_DIR}/$*.out - > $@ ; \
+		if [ $$? = 0 ]; \
+			then echo "OK"; \
+			else echo "FAILED:"; cat $@; \
+		fi; \
+	else \
+		echo " -- SKIPPED"; \
+		touch $@; \
+	fi
 
 ${OUTPUT_DIR}/%.out: ${TARGET} ${TEST_DIR}/%${EXT}
 	-@test -f $@ || echo "$@:"
